CONTRACTIONS = {
    "you are": "you're",
    "i am": "i'm",
    "he is": "he's",
    "she is": "she's",
    "they are": "they're",
    "we are": "we're",
    "it is": "it's",
    "do not": "don't",
    "does not": "doesn't",
    "did not": "didn't",
    "will not": "won't",
    "can not": "can't",
    "cannot": "can't",
    "i have": "i've",
    "you have": "you've",
    "we have": "we've",
    "they have": "they've",
    "i would": "i'd",
    "you would": "you'd",
    "he would": "he'd",
    "that is": "that's",
    "there is": "there's",
    "what is": "what's",
}


REPORT_FILES = [
    "UserScore/RegisteredGroups.xlsx",
    "UserScore/thoughts.xlsx",
    "UserScore/user_streaks.xlsx",
    "UserScore/translationpracticescore.xlsx",
    "UserScore/easytranslateSentences.xlsx",
    "UserScore/mediumtranslateSentences.xlsx",
    "UserScore/hardtranslateSentences.xlsx",
    "UserScore/rar_daily_usage.xlsx",
    "Data/payment.jpg" ,
    "UserScore/speechscore.xlsx",
    "UserScore/premium_tokens.xlsx",
    "Data/reading_paragraphs.xlsx",
    "UserScore/quiz_master.xlsx"
]